import fs from "node:fs";
import path from "node:path";
import { defaultManifestPath, resourceSkillRoot } from "./paths.js";
import {
  type ResourceConfig,
  type ResourceManifest,
  resourceManifestSchema,
} from "./types.js";

export function loadResourceManifest(
  manifestPath = defaultManifestPath(),
): ResourceManifest {
  const raw = fs.readFileSync(manifestPath, "utf8");
  const parsed = resourceManifestSchema.safeParse(JSON.parse(raw));
  if (!parsed.success) {
    throw new Error(`Invalid resource manifest: ${parsed.error.message}`);
  }
  return parsed.data;
}

export function selectResources(
  manifest: ResourceManifest,
  selector = "all",
): ResourceConfig[] {
  if (selector === "all") return manifest.resources;
  if (selector === "fixtures") {
    return manifest.resources.filter((resource) =>
      resource.tags.includes("fixture"),
    );
  }
  const resource = manifest.resources.find((item) => item.slug === selector);
  if (!resource) {
    throw new Error(`Unknown resource '${selector}'`);
  }
  return [resource];
}

export function skillPathForResource(
  resource: ResourceConfig,
  skillRoot = resourceSkillRoot(),
): string {
  return path.join(skillRoot, resource.skill_path);
}

export function readResourceSkill(
  resource: ResourceConfig,
  skillRoot = resourceSkillRoot(),
): { path: string; exists: boolean; text: string | null } {
  const fullPath = skillPathForResource(resource, skillRoot);
  if (!fs.existsSync(fullPath)) {
    return { path: fullPath, exists: false, text: null };
  }
  return { path: fullPath, exists: true, text: fs.readFileSync(fullPath, "utf8") };
}

export function ensureResourceSkill(
  resource: ResourceConfig,
  skillRoot = resourceSkillRoot(),
  dryRun = false,
): { path: string; created: boolean } {
  const fullPath = skillPathForResource(resource, skillRoot);
  if (fs.existsSync(fullPath)) return { path: fullPath, created: false };
  const lines = [
    `# ${resource.title} — Extraction`,
    "",
    `Resource: \`${resource.repo}\``,
    "",
    "## Access Path",
    "",
    "- Use GitHub API for tree listing.",
    "- Use `raw.githubusercontent.com` for Markdown content.",
    `- Default branch is \`${resource.branch}\`.`,
    "",
    "## Include",
    "",
    ...resource.include_paths.map((item) => `- \`${item}\``),
    "",
    "## Exclude",
    "",
    ...(resource.exclude_paths.length
      ? resource.exclude_paths.map((item) => `- \`${item}\``)
      : ["- None configured."]),
    "",
    "## Notes",
    "",
    "- Generated by the resource assessment step.",
    "- Update this file with durable access paths, traps, selectors, and rate limits as they are discovered.",
  ];
  if (!dryRun) {
    fs.mkdirSync(path.dirname(fullPath), { recursive: true });
    fs.writeFileSync(fullPath, `${lines.join("\n")}\n`, "utf8");
  }
  return { path: fullPath, created: true };
}
